[package]
name = "tx-client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.24", features = ["rt", "net"] }
tx-common = { path = "../tx-common" }
env_logger = "0.10.0"
rand = "0.8.5"
log = "0.4.17"